services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yadra-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./conf.yaml:/app/conf.yaml
    restart: unless-stopped
    networks:
      - yadra-network

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
    container_name: yadra-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - yadra-network

networks:
  yadra-network:
    driver: bridge
