name: 🐛 Bug Report
description: Report a bug to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: 🐛 What happened?
      description: A clear description of what the bug is
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected behavior
      description: What did you expect to happen?
      placeholder: What should happen?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📋 Relevant logs
      description: Please copy and paste any relevant log output
      render: shell

  - type: dropdown
    id: component
    attributes:
      label: 🏗️ Component
      description: Which component is affected?
      options:
        - Frontend (Web UI)
        - Backend (API/LangGraph)
        - Database
        - Deployment/Docker
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Environment
      description: Please provide your environment details
      value: |
        - OS: 
        - Python version: 
        - Node.js version: 
        - Browser: 
        - YADRA version/branch: 
      render: markdown
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 Additional context
      description: Add any other context about the problem here